clear all; close all; clc

% -------------------------
% SCRIPT PARAMETER
% -------------------------
params = struct( ...
    ... 
    ... % File parameters, with relative paths
    'videos_folder', "data/26.11", ...
    'results_folder', "results/26.11.filled.thickness", ...
    'reference_path', "reference.JPG", ...
    ...
    ... % Video parameters, in seconds
    'video_init', 0, ...
    'video_end', -1, ...
    ...
    ... % Filtering parameters
    ... % Do not forget to adjust the threshold with debugging, for each capture session
    'threshold', 70, ...
    ... % Type:
    ... % 1 : pixel > threshold
    ... % -1 : pixel < threshold (- pixel > -threshold)
    'threshold_type', 1, ...
    'pixels_channel', 1, ...
    'pixels_filling', 1, ...
    ...
    ...% Analysis to perform
    'static_analysis', 1, ...
    'thickness_analysis', 1, ...
    ...
    ... % Cropping parameters
    'y_min', 200, ...
    'y_max', 3000, ...
    ...
    'x_min', 600, ...
    'x_max', 1300, ...
    ...
    ...% Debugging parameters
    'pause_on_debug', 0, ...
    'fullscreen', 0, ...
    'debug', 0 ...
);

open_videos(params)
