clear all; close all; clc

% -------------------------
% SCRIPT PARAMETER
% -------------------------
params = struct( ...
    ... 
    ... % File parameters, with relative paths
    'videos_folder', "data/26.11", ... % Where are all the videos, relative to the opened folder in MATLAB
    'results_folder', "results/26.11.filled.thickness", ... % Where to save the calculation, relative to the opened folder in MATLAB
    'reference_path', "reference.JPG", ... % Path to the reference image, relative to the opened folder in MATLAB
    ...
    ... % Video parameters (/!\ this applies to all videos), in seconds
    'video_init', 0, ...
    'video_end', -1, ...
    ...
    ... % Threshold for filtering: a number between 0 and 255
    'threshold', 70, ...
    ... % Type of filtering
    ... % 1 : pixel is retained if pixel > threshold
    ... % -1 : pixel is retained if pixel < threshold
    'threshold_type', 1, ...
    % Color channel on which to apply the threshold: 1 for Red, 2 for Green, 3 for Blue
    'pixels_channel', 1, ...
    % Whether to fill blank spaces horizontally between two pixels (0 / 1)
    'pixels_filling', 1, ...
    ...
    ...% Analysis to perform (0 / 1)
    'static_analysis', 1, ... % Area, perimeter, centroid per time step
    'thickness_analysis', 1, ... % Thickness, so the number of pixels per horizontal line, per time step
    ...
    ... % Cropping parameters (/!\ this applies to all videos), in pixels
    'y_min', 200, ...
    'y_max', 3000, ...
    'x_min', 600, ...
    'x_max', 1300, ...
    ...
    ... % Debugging parameters (0 / 1)
    'debug', 0, ... % Whether to display a plot with filtering steps ; this serves to adjust the filtering parameters before proceeding to the full calculation
    'pause_on_debug', 0, ...
    'fullscreen', 0 ...
);

open_videos(params)
